version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile.env
      context: ./server
    restart: always
    ports:
      - 4000:4000
    networks: 
      - backend
    volumes:
      - ~/app:/app
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.env
      context: ./client
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=minz
      - MONGO_INITDB_ROOT_PASSWORD=1205360
    networks:
      - backend

networks: 
  backend:
    driver: bridge